import type { Topic } from './types';

export const TOPICS_STANDARD: Topic[] = [
  // 동물
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '기린', en: 'Giraffe', zh: '长颈鹿' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '코끼리', en: 'Elephant', zh: '大象' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '펭귄', en: 'Penguin', zh: '企鹅' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '문어', en: 'Octopus', zh: '章鱼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '고릴라', en: 'Gorilla', zh: '大猩猩' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '나비', en: 'Butterfly', zh: '蝴蝶' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '악어', en: 'Crocodile', zh: '鳄鱼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '공작새', en: 'Peacock', zh: '孔雀' } },
  // 음식
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '피자', en: 'Pizza', zh: '披萨' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '초밥', en: 'Sushi', zh: '寿司' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '케이크', en: 'Cake', zh: '蛋糕' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '아이스크림', en: 'Ice Cream', zh: '冰淇淋' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '햄버거', en: 'Hamburger', zh: '汉堡' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '라면', en: 'Ramen', zh: '拉面' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '당근', en: 'Carrot', zh: '胡萝卜' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '수박', en: 'Watermelon', zh: '西瓜' } },
  // 유명 건축물 / 자연 명소
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '에펠탑', en: 'Eiffel Tower', zh: '埃菲尔铁塔' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '피라미드', en: 'Pyramid', zh: '金字塔' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '등대', en: 'Lighthouse', zh: '灯塔' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '화산', en: 'Volcano', zh: '火山' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '폭포', en: 'Waterfall', zh: '瀑布' } },
  // 직업
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '소방관', en: 'Firefighter', zh: '消防员' } },
  { category: { ko: '직업', en: 'Job', zh: '职업' }, word: { ko: '요리사', en: 'Chef', zh: '厨师' } },
  { category: { ko: '직업', en: 'Job', zh: '职업' }, word: { ko: '우주비행사', en: 'Astronaut', zh: '宇航员' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '마술사', en: 'Magician', zh: '魔术师' } },
  // 탈것
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '헬리콥터', en: 'Helicopter', zh: '直升机' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '잠수함', en: 'Submarine', zh: '潜水艇' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '열기구', en: 'Hot Air Balloon', zh: '热气球' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '범선', en: 'Sailboat', zh: '帆船' } },
  // 물건
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '기타', en: 'Guitar', zh: '吉他' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '망원경', en: 'Telescope', zh: '望远镜' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '왕관', en: 'Crown', zh: '皇冠' } },
  { category: { ko: '물건', en: 'Object', zh: '物품' }, word: { ko: '자물쇠', en: 'Padlock', zh: '锁' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '모래시계', en: 'Hourglass', zh: '沙漏' } },
  // 자연
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '무지개', en: 'Rainbow', zh: '彩虹' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '번개', en: 'Lightning', zh: '闪电' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '토네이도', en: 'Tornado', zh: '龙卷风' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '오로라', en: 'Aurora', zh: '极光' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '해변', en: 'Beach', zh: '海滩' } },
  // 추가
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '상어', en: 'Shark', zh: '鲨鱼' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '기차', en: 'Train', zh: '火车' } },
  // 동물 추가
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '독수리', en: 'Eagle', zh: '鹰' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '하마', en: 'Hippopotamus', zh: '河马' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '홍학', en: 'Flamingo', zh: '火烈鸟' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '북극곰', en: 'Polar Bear', zh: '北极熊' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '캥거루', en: 'Kangaroo', zh: '袋鼠' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '해파리', en: 'Jellyfish', zh: '水母' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '앵무새', en: 'Parrot', zh: '鹦鹉' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '치타', en: 'Cheetah', zh: '猎豹' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '판다', en: 'Panda', zh: '熊猫' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '거북이', en: 'Turtle', zh: '乌龟' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '전갈', en: 'Scorpion', zh: '蝎子' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '돌고래', en: 'Dolphin', zh: '海豚' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '낙타', en: 'Camel', zh: '骆驼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '라마', en: 'Llama', zh: '羊驼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '두꺼비', en: 'Toad', zh: '蟾蜍' } },
  // 음식 추가
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '타코', en: 'Taco', zh: '墨西哥卷饼' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '파스타', en: 'Pasta', zh: '意大利面' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '도넛', en: 'Donut', zh: '甜甜圈' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '마카롱', en: 'Macaron', zh: '马卡龙' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '팝콘', en: 'Popcorn', zh: '爆米花' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '스테이크', en: 'Steak', zh: '牛排' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '만두', en: 'Dumpling', zh: '饺子' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '된장찌개', en: 'Doenjang Jjigae', zh: '大酱汤' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '불고기', en: 'Bulgogi', zh: '烤牛肉' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '바게트', en: 'Baguette', zh: '法棍' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '와플', en: 'Waffle', zh: '华夫饼' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '샌드위치', en: 'Sandwich', zh: '三明治' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '카레', en: 'Curry', zh: '咖喱' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '파인애플', en: 'Pineapple', zh: '菠萝' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '버섯', en: 'Mushroom', zh: '蘑菇' } },
  // 명소 추가
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '콜로세움', en: 'Colosseum', zh: '罗马竞技场' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '자유의 여신상', en: 'Statue of Liberty', zh: '自由女神像' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '만리장성', en: 'Great Wall of China', zh: '长城' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '타지마할', en: 'Taj Mahal', zh: '泰姬陵' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '빅벤', en: 'Big Ben', zh: '大本钟' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '시드니 오페라하우스', en: 'Sydney Opera House', zh: '悉尼歌剧院' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '파르테논 신전', en: 'Parthenon', zh: '帕台农神庙' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '나이아가라 폭포', en: 'Niagara Falls', zh: '尼亚加拉瀑布' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '그랜드 캐니언', en: 'Grand Canyon', zh: '大峡谷' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '사파리', en: 'Safari', zh: '野生动物园' } },
  // 직업 추가
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '의사', en: 'Doctor', zh: '医生' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '경찰관', en: 'Police Officer', zh: '警察' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '교사', en: 'Teacher', zh: '老师' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '농부', en: 'Farmer', zh: '农民' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '간호사', en: 'Nurse', zh: '护士' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '변호사', en: 'Lawyer', zh: '律师' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '건축가', en: 'Architect', zh: '建筑师' } },
  { category: { ko: '직업', en: 'Job', zh: '职업' }, word: { ko: '파일럿', en: 'Pilot', zh: '飞行员' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '과학자', en: 'Scientist', zh: '科学家' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '음악가', en: 'Musician', zh: '音乐家' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '화가', en: 'Painter', zh: '画家' } },
  { category: { ko: '직업', en: 'Job', zh: '职업' }, word: { ko: '배우', en: 'Actor', zh: '演员' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '운동선수', en: 'Athlete', zh: '运动员' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '사진작가', en: 'Photographer', zh: '摄影师' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '해적', en: 'Pirate', zh: '海盗' } },
  // 탈것 추가
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '오토바이', en: 'Motorcycle', zh: '摩托车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '트랙터', en: 'Tractor', zh: '拖拉机' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '우주선', en: 'Spaceship', zh: '宇宙飞船' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '자전거', en: 'Bicycle', zh: '自行车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '카누', en: 'Canoe', zh: '独木舟' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '비행기', en: 'Airplane', zh: '飞机' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '스쿠터', en: 'Scooter', zh: '滑板车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '탱크', en: 'Tank', zh: '坦克' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '케이블카', en: 'Cable Car', zh: '缆车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '구급차', en: 'Ambulance', zh: '救护车' } },
  // 물건 추가
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '텐트', en: 'Tent', zh: '帐篷' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '나침반', en: 'Compass', zh: '罗盘' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '바이올린', en: 'Violin', zh: '小提琴' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '피아노', en: 'Piano', zh: '钢琴' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '풍선', en: 'Balloon', zh: '气球' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '우산', en: 'Umbrella', zh: '雨伞' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '안경', en: 'Glasses', zh: '眼镜' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '손전등', en: 'Flashlight', zh: '手电筒' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '지도', en: 'Map', zh: '地图' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '열쇠', en: 'Key', zh: '钥匙' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '칫솔', en: 'Toothbrush', zh: '牙刷' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '돋보기', en: 'Magnifying Glass', zh: '放大镜' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '연필', en: 'Pencil', zh: '铅笔' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '수갑', en: 'Handcuffs', zh: '手铐' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '망치', en: 'Hammer', zh: '锤子' } },
  // 자연 추가
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '사막', en: 'Desert', zh: '沙漠' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '빙하', en: 'Glacier', zh: '冰川' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '산호초', en: 'Coral Reef', zh: '珊瑚礁' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '습지', en: 'Swamp', zh: '沼泽' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '동굴', en: 'Cave', zh: '洞穴' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '폭설', en: 'Snowstorm', zh: '暴风雪' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '일식', en: 'Solar Eclipse', zh: '日食' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '선인장', en: 'Cactus', zh: '仙人掌' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '종유석', en: 'Stalactite', zh: '钟乳石' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '별똥별', en: 'Shooting Star', zh: '流星' } },
  // 스포츠
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '축구', en: 'Soccer', zh: '足球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '농구', en: 'Basketball', zh: '篮球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '야구', en: 'Baseball', zh: '棒球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '테니스', en: 'Tennis', zh: '网球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '수영', en: 'Swimming', zh: '游泳' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '체조', en: 'Gymnastics', zh: '体操' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '스키', en: 'Skiing', zh: '滑雪' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '서핑', en: 'Surfing', zh: '冲浪' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '권투', en: 'Boxing', zh: '拳击' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '양궁', en: 'Archery', zh: '射箭' } },
  // 동물 추가2
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '늑대', en: 'Wolf', zh: '狼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '여우', en: 'Fox', zh: '狐狸' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '사슴', en: 'Deer', zh: '鹿' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '코알라', en: 'Koala', zh: '考拉' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '원숭이', en: 'Monkey', zh: '猴子' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '바다표범', en: 'Seal', zh: '海豹' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '뱀', en: 'Snake', zh: '蛇' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '수달', en: 'Otter', zh: '水獭' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '당나귀', en: 'Donkey', zh: '驴' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '타조', en: 'Ostrich', zh: '鸵鸟' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '황소', en: 'Bull', zh: '公牛' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '다람쥐', en: 'Squirrel', zh: '松鼠' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '두루미', en: 'Crane', zh: '鹤' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '코뿔소', en: 'Rhinoceros', zh: '犀牛' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '딱따구리', en: 'Woodpecker', zh: '啄木鸟' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '올빼미', en: 'Owl', zh: '猫头鹰' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '제비', en: 'Swallow', zh: '燕子' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '개구리', en: 'Frog', zh: '青蛙' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '미어캣', en: 'Meerkat', zh: '猫鼬' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '비버', en: 'Beaver', zh: '河狸' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '피라냐', en: 'Piranha', zh: '食人鱼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '가오리', en: 'Stingray', zh: '魟鱼' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '박쥐', en: 'Bat', zh: '蝙蝠' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '메뚜기', en: 'Grasshopper', zh: '蚱蜢' } },
  { category: { ko: '동물', en: 'Animal', zh: '动物' }, word: { ko: '악어거북', en: 'Snapping Turtle', zh: '鳄龟' } },
  // 음식 추가2
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '초콜릿', en: 'Chocolate', zh: '巧克力' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '찐빵', en: 'Steamed Bun', zh: '包子' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '오믈렛', en: 'Omelette', zh: '煎蛋卷' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '돈까스', en: 'Tonkatsu', zh: '炸猪排' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '딸기', en: 'Strawberry', zh: '草莓' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '포도', en: 'Grapes', zh: '葡萄' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '레몬', en: 'Lemon', zh: '柠檬' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '옥수수', en: 'Corn', zh: '玉米' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '호박', en: 'Pumpkin', zh: '南瓜' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '양파', en: 'Onion', zh: '洋葱' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '마늘', en: 'Garlic', zh: '大蒜' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '고추', en: 'Chili Pepper', zh: '辣椒' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '계란', en: 'Egg', zh: '鸡蛋' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '떡볶이', en: 'Tteokbokki', zh: '辣炒年糕' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '김밥', en: 'Kimbap', zh: '紫菜饭卷' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '치킨', en: 'Fried Chicken', zh: '炸鸡' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '오렌지', en: 'Orange', zh: '橙子' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '복숭아', en: 'Peach', zh: '桃子' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '망고', en: 'Mango', zh: '芒果' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '코코넛', en: 'Coconut', zh: '椰子' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '체리', en: 'Cherry', zh: '樱桃' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '브로콜리', en: 'Broccoli', zh: '西兰花' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '감', en: 'Persimmon', zh: '柿子' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '블루베리', en: 'Blueberry', zh: '蓝莓' } },
  { category: { ko: '음식', en: 'Food', zh: '食物' }, word: { ko: '귤', en: 'Tangerine', zh: '橘子' } },
  // 명소 추가2
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '스톤헨지', en: 'Stonehenge', zh: '巨石阵' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '마추픽추', en: 'Machu Picchu', zh: '马丘比丘' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '앙코르와트', en: 'Angkor Wat', zh: '吴哥窟' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '피사의 사탑', en: 'Leaning Tower of Pisa', zh: '比萨斜塔' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '베르사유 궁전', en: 'Palace of Versailles', zh: '凡尔赛宫' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '부르즈 할리파', en: 'Burj Khalifa', zh: '哈利法塔' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '에베레스트 산', en: 'Mount Everest', zh: '珠穆朗玛峰' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '베네치아', en: 'Venice', zh: '威尼斯' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '아마존 강', en: 'Amazon River', zh: '亚马逊河' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '사하라 사막', en: 'Sahara Desert', zh: '撒哈拉沙漠' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '모아이 석상', en: 'Moai Statues', zh: '摩艾石像' } },
  { category: { ko: '명소', en: 'Landmark', zh: '名胜' }, word: { ko: '알함브라 궁전', en: 'Alhambra', zh: '阿尔罕布拉宫' } },
  // 직업 추가2
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '탐정', en: 'Detective', zh: '侦探' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '잠수부', en: 'Diver', zh: '潜水员' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '벌목꾼', en: 'Lumberjack', zh: '伐木工' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '광부', en: 'Miner', zh: '矿工' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '어부', en: 'Fisherman', zh: '渔夫' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '목수', en: 'Carpenter', zh: '木匠' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '제빵사', en: 'Baker', zh: '面包师' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '재봉사', en: 'Tailor', zh: '裁缝' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '기사', en: 'Knight', zh: '骑士' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '선원', en: 'Sailor', zh: '水手' } },
  { category: { ko: '직업', en: 'Job', zh: '职업' }, word: { ko: '탐험가', en: 'Explorer', zh: '探险家' } },
  { category: { ko: '직업', en: 'Job', zh: '职业' }, word: { ko: '판사', en: 'Judge', zh: '法官' } },
  // 탈것 추가2
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '리무진', en: 'Limousine', zh: '豪华轿车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '소방차', en: 'Fire Truck', zh: '消防车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '경찰차', en: 'Police Car', zh: '警车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '덤프트럭', en: 'Dump Truck', zh: '自卸车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '행글라이더', en: 'Hang Glider', zh: '悬挂式滑翔机' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '설상차', en: 'Snowmobile', zh: '雪地摩托' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '외발자전거', en: 'Unicycle', zh: '独轮车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '스케이트보드', en: 'Skateboard', zh: '滑板' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '제트스키', en: 'Jet Ski', zh: '摩托艇' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '마차', en: 'Carriage', zh: '马车' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '썰매', en: 'Sled', zh: '雪橇' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '호버크래프트', en: 'Hovercraft', zh: '气垫船' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '롤러스케이트', en: 'Roller Skates', zh: '旱冰鞋' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '수상스키', en: 'Water Ski', zh: '滑水板' } },
  { category: { ko: '탈것', en: 'Vehicle', zh: '交通工具' }, word: { ko: '잠수정', en: 'Submersible', zh: '潜水器' } },
  // 물건 추가2
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '드럼', en: 'Drum', zh: '鼓' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '플루트', en: 'Flute', zh: '长笛' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '트럼펫', en: 'Trumpet', zh: '小号' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '부채', en: 'Fan', zh: '扇子' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '반지', en: 'Ring', zh: '戒指' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '목걸이', en: 'Necklace', zh: '项链' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '알람시계', en: 'Alarm Clock', zh: '闹钟' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '저울', en: 'Scale', zh: '秤' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '주전자', en: 'Kettle', zh: '水壶' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '화분', en: 'Flower Pot', zh: '花盆' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '빗자루', en: 'Broom', zh: '扫帚' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '등불', en: 'Lantern', zh: '灯笼' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '깃발', en: 'Flag', zh: '旗帜' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '팽이', en: 'Spinning Top', zh: '陀螺' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '요요', en: 'Yo-yo', zh: '溜溜球' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '주사위', en: 'Dice', zh: '骰子' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '조각상', en: 'Statue', zh: '雕像' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '방패', en: 'Shield', zh: '盾牌' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '검', en: 'Sword', zh: '剑' } },
  { category: { ko: '물건', en: 'Object', zh: '物品' }, word: { ko: '활', en: 'Bow', zh: '弓' } },
  // 자연 추가2
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '유성우', en: 'Meteor Shower', zh: '流星雨' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '쓰나미', en: 'Tsunami', zh: '海啸' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '대나무 숲', en: 'Bamboo Forest', zh: '竹林' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '단풍', en: 'Autumn Leaves', zh: '枫叶' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '눈송이', en: 'Snowflake', zh: '雪花' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '모래폭풍', en: 'Sandstorm', zh: '沙尘暴' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '폭풍', en: 'Storm', zh: '暴风雨' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '안개', en: 'Fog', zh: '雾' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '낙엽', en: 'Fallen Leaves', zh: '落叶' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '절벽', en: 'Cliff', zh: '悬崖' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '협곡', en: 'Canyon', zh: '峡谷' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '오아시스', en: 'Oasis', zh: '绿洲' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '갯벌', en: 'Tidal Flat', zh: '潮滩' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '이끼', en: 'Moss', zh: '苔藓' } },
  { category: { ko: '자연', en: 'Nature', zh: '自然' }, word: { ko: '노을', en: 'Sunset', zh: '落日' } },
  // 스포츠 추가2
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '배구', en: 'Volleyball', zh: '排球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '탁구', en: 'Table Tennis', zh: '乒乓球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '골프', en: 'Golf', zh: '高尔夫' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '볼링', en: 'Bowling', zh: '保龄球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '사이클', en: 'Cycling', zh: '自行车赛' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '펜싱', en: 'Fencing', zh: '击剑' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '유도', en: 'Judo', zh: '柔道' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运동' }, word: { ko: '태권도', en: 'Taekwondo', zh: '跆拳道' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '다이빙', en: 'Diving', zh: '跳水' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '암벽등반', en: 'Rock Climbing', zh: '攀岩' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运동' }, word: { ko: '하키', en: 'Hockey', zh: '曲棍球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '럭비', en: 'Rugby', zh: '橄榄球' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '역도', en: 'Weightlifting', zh: '举重' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '레슬링', en: 'Wrestling', zh: '摔跤' } },
  { category: { ko: '스포츠', en: 'Sport', zh: '运动' }, word: { ko: '스케이팅', en: 'Ice Skating', zh: '溜冰' } },
  // 건물
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '성', en: 'Castle', zh: '城堡' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '교회', en: 'Church', zh: '教堂' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '탑', en: 'Tower', zh: '塔' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '다리', en: 'Bridge', zh: '桥' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '댐', en: 'Dam', zh: '水坝' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '창고', en: 'Barn', zh: '谷仓' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '풍차', en: 'Windmill', zh: '风车' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '온실', en: 'Greenhouse', zh: '温室' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '도서관', en: 'Library', zh: '图书馆' } },
  { category: { ko: '건물', en: 'Building', zh: '建筑' }, word: { ko: '극장', en: 'Theater', zh: '剧院' } },
  // 날씨
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '소나기', en: 'Shower', zh: '阵雨' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '우박', en: 'Hail', zh: '冰雹' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '이슬비', en: 'Drizzle', zh: '毛毛雨' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '태풍', en: 'Typhoon', zh: '台风' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '황사', en: 'Yellow Dust', zh: '沙尘' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '서리', en: 'Frost', zh: '霜' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '무더위', en: 'Heat Wave', zh: '酷暑' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '이슬', en: 'Dew', zh: '露水' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '회오리', en: 'Whirlwind', zh: '旋风' } },
  { category: { ko: '날씨', en: 'Weather', zh: '天气' }, word: { ko: '구름', en: 'Cloud', zh: '云' } },
];
