import type { Topic } from './types';

export const TOPICS_JW: Topic[] = [
  // 성경 인물
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '노아', en: 'Noah', zh: '挪亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '다윗', en: 'David', zh: '大卫' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '모세', en: 'Moses', zh: '摩西' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '요나', en: 'Jonah', zh: '约拿' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '삼손', en: 'Samson', zh: '参孙' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '룻', en: 'Ruth', zh: '路得' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '에스더', en: 'Esther', zh: '以斯帖' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '다니엘', en: 'Daniel', zh: '但以理' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '엘리야', en: 'Elijah', zh: '以利亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '솔로몬', en: 'Solomon', zh: '所罗门' } },
  // 성경 물건
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '방주', en: 'Ark', zh: '方舟' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '언약궤', en: 'Ark of the Covenant', zh: '约柜' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '물매', en: 'Sling', zh: '弹弓' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '나팔', en: 'Trumpet', zh: '号角' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '만나', en: 'Manna', zh: '吗哪' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '등잔대', en: 'Lampstand', zh: '灯台' } },
  // 성경 장소
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '에덴동산', en: 'Garden of Eden', zh: '伊甸园' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '갈릴리 호수', en: 'Sea of Galilee', zh: '加利利海' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '시내산', en: 'Mount Sinai', zh: '西奈山' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '예루살렘 성전', en: 'Jerusalem Temple', zh: '耶路撒冷圣殿' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '베들레헴', en: 'Bethlehem', zh: '伯利恒' } },
  // 성경 사건
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '홍해를 가름', en: 'Parting the Red Sea', zh: '分开红海' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '오병이어', en: 'Feeding 5000', zh: '五饼二鱼' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '사자굴에서 구출', en: 'Rescued from Lions', zh: '从狮子坑被救' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '물이 포도주로', en: 'Water into Wine', zh: '水变成酒' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '여리고 성벽 붕괴', en: 'Walls of Jericho', zh: '耶利哥城墙倒塌' } },
  // JW 활동
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '전도', en: 'Preaching', zh: '传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '기념식', en: 'Memorial', zh: '纪念聚会' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '침례', en: 'Baptism', zh: '受浸' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '대회', en: 'Convention', zh: '大会' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '왕국회관', en: 'Kingdom Hall', zh: '王国聚会所' } },
  // 추가 성경 인물
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아브라함', en: 'Abraham', zh: '亚伯拉罕' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '요셉', en: 'Joseph', zh: '约瑟' } },
  // 성경 인물 추가
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '이삭', en: 'Isaac', zh: '以撒' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '야곱', en: 'Jacob', zh: '雅各' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '리브가', en: 'Rebekah', zh: '利百加' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '라헬', en: 'Rachel', zh: '拉结' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '레아', en: 'Leah', zh: '利亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '요한', en: 'John', zh: '约翰' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '베드로', en: 'Peter', zh: '彼得' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '바울', en: 'Paul', zh: '保罗' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '여호수아', en: 'Joshua', zh: '约书亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '기드온', en: 'Gideon', zh: '基甸' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '드보라', en: 'Deborah', zh: '底波拉' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '한나', en: 'Hannah', zh: '哈拿' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '사무엘', en: 'Samuel', zh: '撒母耳' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '사울', en: 'Saul', zh: '扫罗' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '요나단', en: 'Jonathan', zh: '约拿单' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아비가일', en: 'Abigail', zh: '亚比该' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '엘리사', en: 'Elisha', zh: '以利沙' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '예레미야', en: 'Jeremiah', zh: '耶利米' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '이사야', en: 'Isaiah', zh: '以赛亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '에스라', en: 'Ezra', zh: '以斯拉' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '느헤미야', en: 'Nehemiah', zh: '尼希米' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '막달라 마리아', en: 'Mary Magdalene', zh: '抹大拉的马利亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '마르다', en: 'Martha', zh: '马大' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '라합', en: 'Rahab', zh: '喇合' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '스데반', en: 'Stephen', zh: '司提反' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '바나바', en: 'Barnabas', zh: '巴拿巴' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '디모데', en: 'Timothy', zh: '提摩太' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '실라', en: 'Silas', zh: '西拉' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '아굴라', en: 'Aquila', zh: '亚居拉' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '힐기야', en: 'Hilkiah', zh: '希勒家' } },
  // 성경 물건 추가
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '제단', en: 'Altar', zh: '祭坛' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '몰약', en: 'Myrrh', zh: '没药' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '유향', en: 'Frankincense', zh: '乳香' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '성막', en: 'Tabernacle', zh: '会幕' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '속죄소', en: 'Mercy Seat', zh: '施恩座' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '쟁기', en: 'Plow', zh: '犁' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '놋뱀', en: 'Bronze Snake', zh: '铜蛇' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '문설주', en: 'Doorpost', zh: '门框' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '두루마리', en: 'Scroll', zh: '卷轴' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '인장', en: 'Seal', zh: '印章' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '수금', en: 'Harp', zh: '竖琴' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '타작마당', en: 'Threshing Floor', zh: '禾场' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '기름부음병', en: 'Oil Flask', zh: '油瓶' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '향로', en: 'Incense Burner', zh: '香炉' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '흉패', en: 'Breastpiece', zh: '胸牌' } },
  // 성경 장소 추가
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '여리고', en: 'Jericho', zh: '耶利哥' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '니네베', en: 'Nineveh', zh: '尼尼微' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '바벨론', en: 'Babylon', zh: '巴比伦' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '이집트', en: 'Egypt', zh: '埃及' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '광야', en: 'Wilderness', zh: '旷野' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '요르단강', en: 'Jordan River', zh: '约旦河' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '올리브산', en: 'Mount of Olives', zh: '橄榄山' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '겟세마네', en: 'Gethsemane', zh: '客西马尼' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '골고다', en: 'Golgotha', zh: '各各他' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '가버나움', en: 'Capernaum', zh: '迦百农' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '나사렛', en: 'Nazareth', zh: '拿撒勒' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '에페소', en: 'Ephesus', zh: '以弗所' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '코린트', en: 'Corinth', zh: '科林斯' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '소돔', en: 'Sodom', zh: '所多玛' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '가나', en: 'Cana', zh: '迦拿' } },
  // 성경 사건 추가
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '천지창조', en: 'Creation', zh: '创造天地' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '가인의 아벨 살해', en: 'Cain Kills Abel', zh: '该隐杀亚伯' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '바벨탑', en: 'Tower of Babel', zh: '巴别塔' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '소돔 멸망', en: 'Destruction of Sodom', zh: '所多玛灭亡' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '이삭 번제', en: 'Sacrifice of Isaac', zh: '献以撒' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '이스라엘 과월절', en: 'Passover', zh: '逾越节' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '만나 내림', en: 'Manna Falls', zh: '吗哪降下' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '불기둥 구름기둥', en: 'Pillar of Fire and Cloud', zh: '火柱云柱' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '여호수아의 태양 멈춤', en: 'Sun Stands Still', zh: '太阳停住' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '삼손의 머리 깎임', en: "Samson's Hair Cut", zh: '参孙剪发' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '다윗과 골리앗', en: 'David and Goliath', zh: '大卫与歌利亚' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '솔로몬의 지혜 판결', en: "Solomon's Wise Judgment", zh: '所罗门的明判' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '엘리야의 불', en: 'Elijah Calls Down Fire', zh: '以利亚求降火' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '나아만 문둥병 치유', en: 'Naaman Healed of Leprosy', zh: '乃缦大麻风痊愈' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '느부갓네살의 꿈', en: "Nebuchadnezzar's Dream", zh: '尼布甲尼撒的梦' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '사드락 메삭 아벳느고', en: 'Fiery Furnace', zh: '火窑三人' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '예수 세례', en: "Jesus' Baptism", zh: '耶稣受浸' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '나사로 부활', en: 'Lazarus Raised', zh: '拉撒路复活' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '오순절 성령 강림', en: 'Pentecost', zh: '五旬节' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '룻의 충절', en: "Ruth's Loyalty", zh: '路得的忠诚' } },
  // JW 활동 추가
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '성경공부', en: 'Bible Study', zh: '圣经研究' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '집집 방문', en: 'House-to-House', zh: '挨家挨户' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '잡지 배부', en: 'Magazine Distribution', zh: '分发杂志' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '파수대 공부', en: 'Watchtower Study', zh: '守望台研究' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '신권봉사학교', en: 'Theocratic Ministry School', zh: '神权传道学校' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '봉사 모임', en: 'Service Meeting', zh: '服务会议' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '야외 전도', en: 'Street Witnessing', zh: '街头传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '편지 전도', en: 'Letter Writing Campaign', zh: '写信传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '전화 전도', en: 'Telephone Witnessing', zh: '电话传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: 'JW.ORG 사이트', en: 'JW.ORG Website', zh: 'JW.ORG网站' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '베델 봉사', en: 'Bethel Service', zh: '伯特利服务' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '특별 파이오니아', en: 'Special Pioneer', zh: '特别先驱' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '정규 파이오니아', en: 'Regular Pioneer', zh: '正规先驱' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '보조 파이오니아', en: 'Auxiliary Pioneer', zh: '辅助先驱' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '재해 구호', en: 'Disaster Relief', zh: '灾害救援' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '순회감독자 방문', en: 'Circuit Overseer Visit', zh: '巡回监督访问' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '지역 대회', en: 'Regional Convention', zh: '地区大会' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '성경 드라마', en: 'Bible Drama', zh: '圣经剧' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '회중 기도', en: 'Congregation Prayer', zh: '会众祷告' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '신앙 간증', en: 'Sharing Your Faith', zh: '分享你的信仰' } },
  // 성경 인물 추가2
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아담', en: 'Adam', zh: '亚当' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '하와', en: 'Eve', zh: '夏娃' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아벨', en: 'Abel', zh: '亚伯' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '가인', en: 'Cain', zh: '该隐' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '멜기세덱', en: 'Melchizedek', zh: '麦基洗德' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '롯', en: 'Lot', zh: '罗得' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '하갈', en: 'Hagar', zh: '夏甲' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '이스마엘', en: 'Ishmael', zh: '以实玛利' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '에서', en: 'Esau', zh: '以扫' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '미리암', en: 'Miriam', zh: '米利暗' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '아론', en: 'Aaron', zh: '亚伦' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '갈렙', en: 'Caleb', zh: '迦勒' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '입다', en: 'Jephthah', zh: '耶弗他' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '보아스', en: 'Boaz', zh: '波阿斯' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '나오미', en: 'Naomi', zh: '拿俄米' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '엘리', en: 'Eli', zh: '以利' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '고레스', en: 'Cyrus', zh: '居鲁士' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '느부갓네살', en: 'Nebuchadnezzar', zh: '尼布甲尼撒' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '다리우스', en: 'Darius', zh: '大流士' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아하수에로', en: 'Ahasuerus', zh: '亚哈随鲁' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '빌라도', en: 'Pilate', zh: '彼拉多' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '헤롯', en: 'Herod', zh: '希律' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '나다나엘', en: 'Nathanael', zh: '拿但业' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '도마', en: 'Thomas', zh: '多马' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '야고보', en: 'James', zh: '雅各' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '빌립', en: 'Philip', zh: '腓力' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '안드레', en: 'Andrew', zh: '安得烈' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '리디아', en: 'Lydia', zh: '吕底亚' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '브리스길라', en: 'Priscilla', zh: '百基拉' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아볼로', en: 'Apollos', zh: '亚波罗' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '디도', en: 'Titus', zh: '提多' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '삭개오', en: 'Zacchaeus', zh: '撒该' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '므낫세', en: 'Manasseh', zh: '玛拿西' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人物' }, word: { ko: '아사', en: 'Asa', zh: '亚撒' } },
  { category: { ko: '성경 인물', en: 'Bible Person', zh: '圣经人물' }, word: { ko: '요시야', en: 'Josiah', zh: '约西亚' } },
  // 성경 물건 추가2
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '지팡이', en: 'Staff', zh: '杖' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '은 30개', en: '30 Silver Coins', zh: '三十块银钱' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '투구', en: 'Helmet', zh: '头盔' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '창', en: 'Spear', zh: '矛' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '화살', en: 'Arrow', zh: '箭' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '광주리', en: 'Basket', zh: '篮子' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '돌판', en: 'Stone Tablets', zh: '石板' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '제비', en: 'Lots', zh: '签' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '금 송아지', en: 'Golden Calf', zh: '金牛犊' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '어망', en: 'Fishing Net', zh: '渔网' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '고문주', en: 'Torture Stake', zh: '苦刑柱' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '갑옷', en: 'Armor', zh: '盔甲' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '항아리', en: 'Clay Jar', zh: '陶罐' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '보좌', en: 'Throne', zh: '宝座' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物品' }, word: { ko: '등잔', en: 'Oil Lamp', zh: '油灯' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '밧줄', en: 'Rope', zh: '绳子' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '포도주잔', en: 'Wine Cup', zh: '酒杯' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '방패', en: 'Shield', zh: '盾牌' } },
  { category: { ko: '성경 물건', en: 'Bible Object', zh: '圣经物품' }, word: { ko: '검', en: 'Sword', zh: '剑' } },
  // 성경 장소 추가2
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '아라라트 산', en: 'Mount Ararat', zh: '亚拉拉特山' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '브엘세바', en: 'Beersheba', zh: '别是巴' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '헤브론', en: 'Hebron', zh: '希伯伦' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '다메섹', en: 'Damascus', zh: '大马士革' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '빌립보', en: 'Philippi', zh: '腓立比' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '데살로니가', en: 'Thessalonica', zh: '帖撒罗尼迦' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '로마', en: 'Rome', zh: '罗马' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '아테네', en: 'Athens', zh: '雅典' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '기브온', en: 'Gibeon', zh: '基遍' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '사마리아', en: 'Samaria', zh: '撒玛利亚' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '사해', en: 'Dead Sea', zh: '死海' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '지중해', en: 'Mediterranean Sea', zh: '地中海' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '엠마오', en: 'Emmaus', zh: '以马忤斯' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '가이사랴', en: 'Caesarea', zh: '凯撒利亚' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '드로아', en: 'Troas', zh: '特罗亚' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '멜리데 섬', en: 'Malta', zh: '马耳他' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '밧모 섬', en: 'Patmos', zh: '拔摩岛' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '유다 광야', en: 'Judean Wilderness', zh: '犹太旷野' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地点' }, word: { ko: '아라비아', en: 'Arabia', zh: '阿拉伯' } },
  { category: { ko: '성경 장소', en: 'Bible Place', zh: '圣经地점' }, word: { ko: '가다라', en: 'Gadara', zh: '加大拉' } },
  // 성경 사건 추가2
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '대홍수', en: 'The Great Flood', zh: '大洪水' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '롯의 아내 소금 기둥', en: "Lot's Wife Becomes Salt", zh: '罗得妻变盐柱' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '야곱의 씨름', en: 'Jacob Wrestles', zh: '雅各摔跤' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '요셉의 꿈', en: "Joseph's Dreams", zh: '约瑟的梦' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '요셉의 형제들에게 팔림', en: 'Joseph Sold by Brothers', zh: '约瑟被卖' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '불타는 떨기나무', en: 'Burning Bush', zh: '燃烧的荆棘' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '이집트 재앙', en: 'Plagues of Egypt', zh: '埃及十灾' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '기드온의 300명', en: "Gideon's 300", zh: '基甸的三百人' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '삼손과 데릴라', en: 'Samson and Delilah', zh: '参孙与大利拉' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '한나의 기도', en: "Hannah's Prayer", zh: '哈拿的祷告' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '솔로몬의 성전 건축', en: 'Solomon Builds the Temple', zh: '所罗门建圣殿' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '엘리야의 승천', en: "Elijah's Ascension", zh: '以利亚升天' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经사건' }, word: { ko: '엘리사의 기름 기적', en: "Elisha's Oil Miracle", zh: '以利沙的油奇迹' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '이사야의 환상', en: "Isaiah's Vision", zh: '以赛亚的异象' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '에스더의 용기', en: "Esther's Courage", zh: '以斯帖的勇气' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '느헤미야의 성벽 재건', en: 'Nehemiah Rebuilds the Wall', zh: '尼希米重建城墙' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '동방박사의 방문', en: 'Visit of the Magi', zh: '东方博士来访' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '예수의 광야 시험', en: 'Jesus Tempted in Wilderness', zh: '耶稣在旷野受试探' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '변화산', en: 'Transfiguration', zh: '变形山' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '나인 과부의 아들 부활', en: 'Son of Widow of Nain Raised', zh: '拿因寡妇之子复活' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '눈먼 자 치유', en: 'Healing of Blind Man', zh: '医治盲人' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '나병환자 10명 치유', en: 'Ten Lepers Healed', zh: '治愈十个大麻风病人' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '풍랑을 잠잠케 함', en: 'Calms the Storm', zh: '平息风浪' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '물 위를 걸음', en: 'Walking on Water', zh: '行走水面' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '바울의 회심', en: "Paul's Conversion", zh: '保罗的悔改' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '요한의 환상', en: "John's Vision", zh: '约翰的异象' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '아나니아와 삽비라', en: 'Ananias and Sapphira', zh: '亚拿尼亚与撒非喇' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '야곱의 사닥다리', en: "Jacob's Ladder", zh: '雅各的梯子' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '에덴에서의 추방', en: 'Expelled from Eden', zh: '逐出伊甸' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '가나안 정복', en: 'Conquest of Canaan', zh: '征服迦南' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经사건' }, word: { ko: '히스기야의 기도', en: "Hezekiah's Prayer", zh: '希西家的祷告' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '다니엘의 꿈 해석', en: 'Daniel Interprets Dreams', zh: '但以理解梦' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '바울의 난파', en: "Paul's Shipwreck", zh: '保罗遇难船' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '바울과 실라의 석방', en: 'Paul and Silas Released', zh: '保罗和西拉获释' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '예수의 탄생', en: 'Birth of Jesus', zh: '耶稣的出生' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '예수의 부활', en: 'Resurrection of Jesus', zh: '耶稣复活' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经사건' }, word: { ko: '스데반의 순교', en: "Stephen's Martyrdom", zh: '司提反殉道' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经事件' }, word: { ko: '유월절 양', en: 'Passover Lamb', zh: '逾越节的羔羊' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经사건' }, word: { ko: '사무엘이 다윗에게 기름 부음', en: 'Samuel Anoints David', zh: '撒母耳膏抹大卫' } },
  { category: { ko: '성경 사건', en: 'Bible Event', zh: '圣经사건' }, word: { ko: '엘리사의 도끼 기적', en: 'Elisha Makes Axe Float', zh: '以利沙斧头浮起' } },
  // JW 활동 추가2
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '아침 숙고', en: 'Morning Worship', zh: '早间崇拜' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '가정 예배', en: 'Family Worship', zh: '家庭崇拜' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '비공식 증거', en: 'Informal Witnessing', zh: '非正式见证' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '카트 전도', en: 'Cart Witnessing', zh: '手推车传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '성경 독서', en: 'Bible Reading', zh: '圣经阅读' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '구역 순회', en: 'Territory Work', zh: '区域传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '헌금', en: 'Donation', zh: '捐款' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '회관 건축', en: 'Kingdom Hall Construction', zh: '会堂建设' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '찬송가', en: 'Kingdom Songs', zh: '王国歌' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '온라인 전도', en: 'Online Witnessing', zh: '网络传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '가족 성경 연구', en: 'Family Bible Study', zh: '家庭圣经研究' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '사역 보고', en: 'Field Service Report', zh: '传道报告' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '세례 대화', en: 'Baptism Interview', zh: '受浸访谈' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '지부 봉사', en: 'Branch Service', zh: '分支机构服务' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '특별 집회', en: 'Special Talk', zh: '特别演讲' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '사회봉사', en: 'Community Service', zh: '社区服务' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '봉사자 임명', en: 'Servant Appointment', zh: '仆人任命' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活动' }, word: { ko: '진리 간증', en: 'Testifying to Truth', zh: '见证真理' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '합동 봉사', en: 'Joint Field Service', zh: '联合传道' } },
  { category: { ko: 'JW 활동', en: 'JW Activity', zh: 'JW活동' }, word: { ko: '성경 언어 학습', en: 'Learning Biblical Languages', zh: '学习圣经语言' } },
  // 성경 동물
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '사자', en: 'Lion', zh: '狮子' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '양', en: 'Sheep', zh: '羊' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '비둘기', en: 'Dove', zh: '鸽子' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '까마귀', en: 'Raven', zh: '乌鸦' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '나귀', en: 'Donkey', zh: '驴' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '황소', en: 'Ox', zh: '公牛' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '메뚜기', en: 'Locust', zh: '蝗虫' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '독수리', en: 'Eagle', zh: '鹰' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '물고기', en: 'Fish', zh: '鱼' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '어린 양', en: 'Lamb', zh: '小羊' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '곰', en: 'Bear', zh: '熊' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '표범', en: 'Leopard', zh: '豹' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '전갈', en: 'Scorpion', zh: '蝎子' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '개구리', en: 'Frog', zh: '青蛙' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '낙타', en: 'Camel', zh: '骆驼' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动물' }, word: { ko: '염소', en: 'Goat', zh: '山羊' } },
  { category: { ko: '성경 동물', en: 'Bible Animal', zh: '圣经动物' }, word: { ko: '뱀', en: 'Serpent', zh: '蛇' } },
  // 성경 식물
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '올리브나무', en: 'Olive Tree', zh: '橄榄树' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '무화과나무', en: 'Fig Tree', zh: '无花果树' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经식물' }, word: { ko: '포도나무', en: 'Grapevine', zh: '葡萄树' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '백향목', en: 'Cedar', zh: '香柏树' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '종려나무', en: 'Palm Tree', zh: '棕榈树' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经식물' }, word: { ko: '겨자', en: 'Mustard Plant', zh: '芥菜' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '밀', en: 'Wheat', zh: '小麦' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '보리', en: 'Barley', zh: '大麦' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经식물' }, word: { ko: '갈대', en: 'Reed', zh: '芦苇' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '아카시아', en: 'Acacia', zh: '皂荚树' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '백합', en: 'Lily', zh: '百合' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经식물' }, word: { ko: '알로에', en: 'Aloe', zh: '芦荟' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '히솝', en: 'Hyssop', zh: '牛膝草' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植물' }, word: { ko: '가시나무', en: 'Thornbush', zh: '荆棘' } },
  { category: { ko: '성경 식물', en: 'Bible Plant', zh: '圣经植物' }, word: { ko: '유향나무', en: 'Frankincense Tree', zh: '乳香树' } },
];
